package com.ninni.barnyard.client.animation;

import net.fabricmc.api.EnvType;
import net.fabricmc.api.Environment;
import net.minecraft.client.animation.AnimationChannel;
import net.minecraft.client.animation.AnimationDefinition;
import net.minecraft.client.animation.Keyframe;
import net.minecraft.client.animation.KeyframeAnimations;

import static net.minecraft.client.model.geom.PartNames.*;

@Environment(EnvType.CLIENT)
public class BarnyardPigAnimations {

    public static final AnimationDefinition SNIFFING = AnimationDefinition.Builder.withLength(5.5f)
            .addAnimation(BODY,
                    new AnimationChannel(AnimationChannel.Targets.POSITION,
                            new Keyframe(2.5f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(2.875f, KeyframeAnimations.posVec(0f, -1f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(5.125f, KeyframeAnimations.posVec(0f, -1f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(5.5f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR))
            )
            .addAnimation(BODY,
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.20834334f, KeyframeAnimations.degreeVec(2.5f, 10f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.7083434f, KeyframeAnimations.degreeVec(2.5f, 10f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.9583434f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.1676667f, KeyframeAnimations.degreeVec(2.5f, -10f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.7083433f, KeyframeAnimations.degreeVec(2.5f, -10f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.375f, KeyframeAnimations.degreeVec(5f, 0f, -10f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.75f, KeyframeAnimations.degreeVec(15f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3.0416765f, KeyframeAnimations.degreeVec(15f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3.1676665f, KeyframeAnimations.degreeVec(25f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3.2916765f, KeyframeAnimations.degreeVec(15f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3.4167665f, KeyframeAnimations.degreeVec(25f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3.5416765f, KeyframeAnimations.degreeVec(15f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3.6766665f, KeyframeAnimations.degreeVec(25f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3.7916765f, KeyframeAnimations.degreeVec(15f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3.9167665f, KeyframeAnimations.degreeVec(25f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(4.083433f, KeyframeAnimations.degreeVec(32.5f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(4.167667f, KeyframeAnimations.degreeVec(10f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(4.25f, KeyframeAnimations.degreeVec(5f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(4.75f, KeyframeAnimations.degreeVec(15f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(5f, KeyframeAnimations.degreeVec(5f, 0f, -10f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(5.291677f, KeyframeAnimations.degreeVec(1.4942946400351502f, -0.13071879413337228f, 1.998295305933425f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(5.416767f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM))
            )
            .addAnimation(LEFT_EAR,
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0.08343333f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.2916767f, KeyframeAnimations.degreeVec(-17.5f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.7916766f, KeyframeAnimations.degreeVec(-17.5f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.0416767f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.25f, KeyframeAnimations.degreeVec(-17.5f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.7916767f, KeyframeAnimations.degreeVec(-17.5f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.0416765f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.875f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3.0834335f, KeyframeAnimations.degreeVec(15f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(4.343333f, KeyframeAnimations.degreeVec(15f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(4.541677f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM))
            )
            .addAnimation(RIGHT_EAR,
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.20834334f, KeyframeAnimations.degreeVec(-17.5f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.7083434f, KeyframeAnimations.degreeVec(-17.5f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.9583434f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.1676667f, KeyframeAnimations.degreeVec(-17.5f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.7083433f, KeyframeAnimations.degreeVec(-17.5f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.9583433f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.7916765f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3f, KeyframeAnimations.degreeVec(15f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(4.25f, KeyframeAnimations.degreeVec(15f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(4.458343f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM))
            )
            .addAnimation(NOSE,
                    new AnimationChannel(AnimationChannel.Targets.POSITION,
                            new Keyframe(0.25f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.375f, KeyframeAnimations.posVec(0f, 0f, 0.75f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.5f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.625f, KeyframeAnimations.posVec(0f, 0f, 0.75f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.75f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.2083433f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.3433333f, KeyframeAnimations.posVec(0f, 0f, 0.75f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.4583433f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.5834333f, KeyframeAnimations.posVec(0f, 0f, 0.75f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.7083433f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM))
            )
            .addAnimation(TAIL,
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(3.0416765f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3.25f, KeyframeAnimations.degreeVec(0f, -32.5f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3.4583435f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3.6766665f, KeyframeAnimations.degreeVec(0f, 32.5f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3.9167665f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(4.125f, KeyframeAnimations.degreeVec(0f, -32.5f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(4.343333f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM))
            )
            .addAnimation(LEFT_ARM,
                    new AnimationChannel(AnimationChannel.Targets.POSITION,
                            new Keyframe(2.5f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(2.75f, KeyframeAnimations.posVec(0f, -2f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(5.125f, KeyframeAnimations.posVec(0f, -2f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(5.375f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR))
            )
            .addAnimation(LEFT_ARM,
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(2.375f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(2.625f, KeyframeAnimations.degreeVec(90f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(5.25f, KeyframeAnimations.degreeVec(90f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(5.5f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR))
            )
            .addAnimation(RIGHT_ARM,
                    new AnimationChannel(AnimationChannel.Targets.POSITION,
                            new Keyframe(2.125f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(2.375f, KeyframeAnimations.posVec(0f, -2f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(4.708343f, KeyframeAnimations.posVec(0f, -2f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(4.958343f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR))
            )
            .addAnimation(RIGHT_ARM,
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(2f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(2.25f, KeyframeAnimations.degreeVec(90f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(4.834333f, KeyframeAnimations.degreeVec(90f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(5.083433f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR))
            ).build();


        public static final AnimationDefinition ROLL_IN_MUD = AnimationDefinition.Builder.withLength(5.5f)
                .addAnimation(BODY,
                        new AnimationChannel(AnimationChannel.Targets.POSITION,
                                new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.125f, KeyframeAnimations.posVec(0f, 0.5f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.20834334f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.375f, KeyframeAnimations.posVec(0f, -2f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.5f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.7083434f, KeyframeAnimations.posVec(0f, 4.64f, 0f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(1.0834333f, KeyframeAnimations.posVec(0f, -3f, 0f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(2.375f, KeyframeAnimations.posVec(0f, -3f, 0f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(5.041677f, KeyframeAnimations.posVec(0f, -3f, 0f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(5.5f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                        AnimationChannel.Interpolations.CATMULLROM)))
                .addAnimation(BODY,
                        new AnimationChannel(AnimationChannel.Targets.ROTATION,
                                new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.375f, KeyframeAnimations.degreeVec(10f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.7083434f, KeyframeAnimations.degreeVec(-15f, 0f, 0f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(0.9167666f, KeyframeAnimations.degreeVec(0f, 0f, -90f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(1.0834333f, KeyframeAnimations.degreeVec(0f, 0f, -180f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(1.375f, KeyframeAnimations.degreeVec(0f, 0f, -190f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(1.625f, KeyframeAnimations.degreeVec(0f, 0f, -180f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(1.875f, KeyframeAnimations.degreeVec(0f, 0f, -170f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(2.125f, KeyframeAnimations.degreeVec(0f, 0f, -180f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(2.375f, KeyframeAnimations.degreeVec(0f, 0f, -190f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(2.625f, KeyframeAnimations.degreeVec(0f, 0f, -270f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(2.875f, KeyframeAnimations.degreeVec(0f, 0f, -280f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(3.0416765f, KeyframeAnimations.degreeVec(0f, 0f, -270f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(3.2083435f, KeyframeAnimations.degreeVec(0f, 0f, -260f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(3.375f, KeyframeAnimations.degreeVec(0f, 0f, -270f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(3.5f, KeyframeAnimations.degreeVec(0f, 0f, -280f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(3.7083435f, KeyframeAnimations.degreeVec(0f, 0f, -180f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(3.9167665f, KeyframeAnimations.degreeVec(0f, 0f, -90f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(4.125f, KeyframeAnimations.degreeVec(0f, 0f, -100f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(4.343333f, KeyframeAnimations.degreeVec(0f, 0f, -90f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(4.541677f, KeyframeAnimations.degreeVec(0f, 0f, -100f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(4.708343f, KeyframeAnimations.degreeVec(0f, 0f, -90f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(4.834333f, KeyframeAnimations.degreeVec(0f, 0f, -80f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(5.041677f, KeyframeAnimations.degreeVec(10f, 0f, 0f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(5.25f, KeyframeAnimations.degreeVec(-15f, 0f, 0f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(5.5f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                        AnimationChannel.Interpolations.CATMULLROM)))
                .addAnimation(LEFT_EAR,
                        new AnimationChannel(AnimationChannel.Targets.ROTATION,
                                new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(0.125f, KeyframeAnimations.degreeVec(-5f, 0f, 0f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(0.20834334f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(0.375f, KeyframeAnimations.degreeVec(45f, 0f, 0f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(0.7083434f, KeyframeAnimations.degreeVec(-55f, 0f, 0f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(0.9167666f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(4.416767f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(4.541677f, KeyframeAnimations.degreeVec(-5f, 0f, 0f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(4.625f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(4.834333f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(5.041677f, KeyframeAnimations.degreeVec(35f, 0f, 0f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(5.25f, KeyframeAnimations.degreeVec(-55f, 0f, 0f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(5.5f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                        AnimationChannel.Interpolations.CATMULLROM)))
                .addAnimation(RIGHT_EAR,
                        new AnimationChannel(AnimationChannel.Targets.ROTATION,
                                new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(0.125f, KeyframeAnimations.degreeVec(-5f, 0f, 0f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(0.20834334f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(0.375f, KeyframeAnimations.degreeVec(45f, 0f, 0f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(0.7083434f, KeyframeAnimations.degreeVec(-55f, 0f, 0f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(0.9167666f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(4.416767f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(4.541677f, KeyframeAnimations.degreeVec(-5f, 0f, 0f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(4.625f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(4.791677f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(5f, KeyframeAnimations.degreeVec(35f, 0f, 0f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(5.208343f, KeyframeAnimations.degreeVec(-55f, 0f, 0f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(5.458343f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                        AnimationChannel.Interpolations.CATMULLROM)))
                .addAnimation(NOSE,
                        new AnimationChannel(AnimationChannel.Targets.POSITION,
                                new Keyframe(1.125f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(1.25f, KeyframeAnimations.posVec(0f, 0f, 0.75f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(1.375f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(1.5f, KeyframeAnimations.posVec(0f, 0f, 0.75f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(1.625f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(2.875f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(3f, KeyframeAnimations.posVec(0f, 0f, 0.75f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(3.125f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(3.25f, KeyframeAnimations.posVec(0f, 0f, 0.75f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(3.375f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(3.875f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(4f, KeyframeAnimations.posVec(0f, 0f, 0.75f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(4.125f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(4.25f, KeyframeAnimations.posVec(0f, 0f, 0.75f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(4.375f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                        AnimationChannel.Interpolations.CATMULLROM)))
                .addAnimation(TAIL,
                        new AnimationChannel(AnimationChannel.Targets.ROTATION,
                                new Keyframe(2.375f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(2.625f, KeyframeAnimations.degreeVec(0f, 45f, 0f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(3.5f, KeyframeAnimations.degreeVec(0f, 45f, 0f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(3.7083435f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(3.9583435f, KeyframeAnimations.degreeVec(0f, -45f, 0f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(4.834333f, KeyframeAnimations.degreeVec(0f, -45f, 0f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(5.25f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                        AnimationChannel.Interpolations.CATMULLROM)))
                .addAnimation(LEFT_ARM,
                        new AnimationChannel(AnimationChannel.Targets.POSITION,
                                new Keyframe(0.5f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.7083434f, KeyframeAnimations.posVec(0f, 4.64f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.875f, KeyframeAnimations.posVec(0.8900000000000001f, 6.36f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.0834333f, KeyframeAnimations.posVec(-7f, 4f, 0f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(2.375f, KeyframeAnimations.posVec(-7f, 4f, 0f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(2.625f, KeyframeAnimations.posVec(-8f, -2.66f, 0f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(3.5f, KeyframeAnimations.posVec(-8f, -2.66f, 0f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(3.7083435f, KeyframeAnimations.posVec(-7f, 4f, 0f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(3.9167665f, KeyframeAnimations.posVec(0f, 3.91f, 0f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(4.834333f, KeyframeAnimations.posVec(0f, 3.91f, 0f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(5.083433f, KeyframeAnimations.posVec(0f, -3f, 0f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(5.5f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                        AnimationChannel.Interpolations.CATMULLROM)))
                .addAnimation(LEFT_ARM,
                        new AnimationChannel(AnimationChannel.Targets.ROTATION,
                                new Keyframe(0.7083434f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.0834333f, KeyframeAnimations.degreeVec(9f, 0f, -180f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(1.2083433f, KeyframeAnimations.degreeVec(22.5f, 0f, -180f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(1.4167667f, KeyframeAnimations.degreeVec(0f, 0f, -180f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(1.625f, KeyframeAnimations.degreeVec(-22.5f, 0f, -180f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(1.8343333f, KeyframeAnimations.degreeVec(0f, 0f, -180f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(2.0416765f, KeyframeAnimations.degreeVec(22.5f, 0f, -180f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(2.375f, KeyframeAnimations.degreeVec(0f, 0f, -180f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(2.625f, KeyframeAnimations.degreeVec(0f, 0f, -315f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(2.75f, KeyframeAnimations.degreeVec(0f, 0f, -310f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(2.9583435f, KeyframeAnimations.degreeVec(22.5f, 0f, -310f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(3.1676665f, KeyframeAnimations.degreeVec(0f, 0f, -310f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(3.3433335f, KeyframeAnimations.degreeVec(-22.5f, 0f, -310f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(3.5f, KeyframeAnimations.degreeVec(0f, 0f, -315f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(3.7083435f, KeyframeAnimations.degreeVec(9f, 0f, -180f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(3.9167665f, KeyframeAnimations.degreeVec(0f, 0f, -45f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(4.083433f, KeyframeAnimations.degreeVec(0f, 0f, -40f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(4.291677f, KeyframeAnimations.degreeVec(22.5f, 0f, -40f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(4.458343f, KeyframeAnimations.degreeVec(0f, 0f, -40f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(4.625f, KeyframeAnimations.degreeVec(-22.5f, 0f, -40f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(4.834333f, KeyframeAnimations.degreeVec(0f, 0f, -45f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(5.25f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                        AnimationChannel.Interpolations.CATMULLROM)))
                .addAnimation(LEFT_LEG,
                        new AnimationChannel(AnimationChannel.Targets.POSITION,
                                new Keyframe(0.5f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.7083434f, KeyframeAnimations.posVec(0f, 2.6399999999999997f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.875f, KeyframeAnimations.posVec(2.33f, 6.24f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.0834333f, KeyframeAnimations.posVec(-6f, 4f, 0f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(2.375f, KeyframeAnimations.posVec(-6f, 4f, 0f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(2.625f, KeyframeAnimations.posVec(-7f, -2.66f, 0f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(3.5f, KeyframeAnimations.posVec(-7f, -2.66f, 0f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(3.7083435f, KeyframeAnimations.posVec(-6f, 4f, 0f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(3.9167665f, KeyframeAnimations.posVec(0f, 3.91f, 0f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(4.834333f, KeyframeAnimations.posVec(0f, 3.91f, 0f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(5.083433f, KeyframeAnimations.posVec(0f, -3f, 0f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(5.5f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                        AnimationChannel.Interpolations.CATMULLROM)))
                .addAnimation(LEFT_LEG,
                        new AnimationChannel(AnimationChannel.Targets.ROTATION,
                                new Keyframe(0.7083434f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.0834333f, KeyframeAnimations.degreeVec(9f, 0f, -180f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(1.2083433f, KeyframeAnimations.degreeVec(-22.5f, 0f, -180f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(1.4167667f, KeyframeAnimations.degreeVec(0f, 0f, -180f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(1.625f, KeyframeAnimations.degreeVec(22.5f, 0f, -180f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(1.8343333f, KeyframeAnimations.degreeVec(0f, 0f, -180f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(2.0416765f, KeyframeAnimations.degreeVec(-22.5f, 0f, -180f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(2.375f, KeyframeAnimations.degreeVec(0f, 0f, -180f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(2.625f, KeyframeAnimations.degreeVec(0f, 0f, -315f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(2.75f, KeyframeAnimations.degreeVec(0f, 0f, -310f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(2.9583435f, KeyframeAnimations.degreeVec(-22.5f, 0f, -310f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(3.1676665f, KeyframeAnimations.degreeVec(0f, 0f, -310f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(3.3433335f, KeyframeAnimations.degreeVec(22.5f, 0f, -310f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(3.5f, KeyframeAnimations.degreeVec(0f, 0f, -315f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(3.7083435f, KeyframeAnimations.degreeVec(9f, 0f, -180f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(3.9167665f, KeyframeAnimations.degreeVec(0f, 0f, -45f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(4.083433f, KeyframeAnimations.degreeVec(0f, 0f, -40f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(4.291677f, KeyframeAnimations.degreeVec(-22.5f, 0f, -40f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(4.458343f, KeyframeAnimations.degreeVec(0f, 0f, -40f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(4.625f, KeyframeAnimations.degreeVec(22.5f, 0f, -40f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(4.834333f, KeyframeAnimations.degreeVec(0f, 0f, -45f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(5.25f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                        AnimationChannel.Interpolations.CATMULLROM)))
                .addAnimation(RIGHT_LEG,
                        new AnimationChannel(AnimationChannel.Targets.POSITION,
                                new Keyframe(0.5f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.7083434f, KeyframeAnimations.posVec(0f, 2.6399999999999997f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.875f, KeyframeAnimations.posVec(6.67f, 0.2400000000000002f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.0834333f, KeyframeAnimations.posVec(6f, 4f, 0f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(2.375f, KeyframeAnimations.posVec(6f, 4f, 0f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(2.625f, KeyframeAnimations.posVec(-1f, 3.34f, 0f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(3.5f, KeyframeAnimations.posVec(-1f, 3.34f, 0f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(3.7083435f, KeyframeAnimations.posVec(6f, 4f, 0f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(3.9167665f, KeyframeAnimations.posVec(6f, -3.09f, 0f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(4.834333f, KeyframeAnimations.posVec(6f, -3.09f, 0f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(5.25f, KeyframeAnimations.posVec(0f, -3f, 0f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(5.5f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                        AnimationChannel.Interpolations.CATMULLROM)))
                .addAnimation(RIGHT_LEG,
                        new AnimationChannel(AnimationChannel.Targets.ROTATION,
                                new Keyframe(0.7083434f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.0834333f, KeyframeAnimations.degreeVec(9f, 0f, -180f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(1.2083433f, KeyframeAnimations.degreeVec(22.5f, 0f, -180f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(1.4167667f, KeyframeAnimations.degreeVec(0f, 0f, -180f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(1.625f, KeyframeAnimations.degreeVec(-22.5f, 0f, -180f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(1.8343333f, KeyframeAnimations.degreeVec(0f, 0f, -180f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(2.0416765f, KeyframeAnimations.degreeVec(22.5f, 0f, -180f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(2.375f, KeyframeAnimations.degreeVec(0f, 0f, -180f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(2.625f, KeyframeAnimations.degreeVec(0f, 0f, -315f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(2.75f, KeyframeAnimations.degreeVec(0f, 0f, -310f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(2.9583435f, KeyframeAnimations.degreeVec(22.5f, 0f, -310f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(3.1676665f, KeyframeAnimations.degreeVec(0f, 0f, -310f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(3.3433335f, KeyframeAnimations.degreeVec(-22.5f, 0f, -310f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(3.5f, KeyframeAnimations.degreeVec(0f, 0f, -315f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(3.7083435f, KeyframeAnimations.degreeVec(9f, 0f, -180f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(3.9167665f, KeyframeAnimations.degreeVec(0f, 0f, -45f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(4.083433f, KeyframeAnimations.degreeVec(0f, 0f, -40f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(4.291677f, KeyframeAnimations.degreeVec(22.5f, 0f, -40f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(4.458343f, KeyframeAnimations.degreeVec(0f, 0f, -40f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(4.625f, KeyframeAnimations.degreeVec(-22.5f, 0f, -40f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(4.834333f, KeyframeAnimations.degreeVec(0f, 0f, -45f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(5.25f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                        AnimationChannel.Interpolations.CATMULLROM)))
                .addAnimation(RIGHT_ARM,
                        new AnimationChannel(AnimationChannel.Targets.POSITION,
                                new Keyframe(0.5f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.7083434f, KeyframeAnimations.posVec(0f, 4.64f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.875f, KeyframeAnimations.posVec(7.109999999999999f, 0.3600000000000003f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.0834333f, KeyframeAnimations.posVec(7f, 4f, 0f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(2.375f, KeyframeAnimations.posVec(7f, 4f, 0f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(2.625f, KeyframeAnimations.posVec(-1f, 3.34f, 0f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(3.5f, KeyframeAnimations.posVec(-1f, 3.34f, 0f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(3.7083435f, KeyframeAnimations.posVec(7f, 4f, 0f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(3.9167665f, KeyframeAnimations.posVec(7f, -3.09f, 0f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(4.834333f, KeyframeAnimations.posVec(7f, -3.09f, 0f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(5.25f, KeyframeAnimations.posVec(0f, -3f, 0f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(5.5f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                        AnimationChannel.Interpolations.CATMULLROM)))
                .addAnimation(RIGHT_ARM,
                        new AnimationChannel(AnimationChannel.Targets.ROTATION,
                                new Keyframe(0.7083434f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.0834333f, KeyframeAnimations.degreeVec(9f, 0f, -180f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(1.2083433f, KeyframeAnimations.degreeVec(-22.5f, 0f, -180f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(1.4167667f, KeyframeAnimations.degreeVec(0f, 0f, -180f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(1.625f, KeyframeAnimations.degreeVec(22.5f, 0f, -180f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(1.8343333f, KeyframeAnimations.degreeVec(0f, 0f, -180f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(2.0416765f, KeyframeAnimations.degreeVec(-22.5f, 0f, -180f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(2.375f, KeyframeAnimations.degreeVec(0f, 0f, -180f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(2.625f, KeyframeAnimations.degreeVec(0f, 0f, -315f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(2.75f, KeyframeAnimations.degreeVec(0f, 0f, -310f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(2.9583435f, KeyframeAnimations.degreeVec(-22.5f, 0f, -310f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(3.1676665f, KeyframeAnimations.degreeVec(0f, 0f, -310f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(3.3433335f, KeyframeAnimations.degreeVec(22.5f, 0f, -310f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(3.5f, KeyframeAnimations.degreeVec(0f, 0f, -315f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(3.7083435f, KeyframeAnimations.degreeVec(9f, 0f, -180f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(3.9167665f, KeyframeAnimations.degreeVec(0f, 0f, -45f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(4.083433f, KeyframeAnimations.degreeVec(0f, 0f, -40f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(4.291677f, KeyframeAnimations.degreeVec(-22.5f, 0f, -40f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(4.458343f, KeyframeAnimations.degreeVec(0f, 0f, -40f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(4.625f, KeyframeAnimations.degreeVec(22.5f, 0f, -40f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(4.834333f, KeyframeAnimations.degreeVec(0f, 0f, -45f),
                                        AnimationChannel.Interpolations.CATMULLROM),
                                new Keyframe(5.25f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                        AnimationChannel.Interpolations.CATMULLROM))).build();

}
